apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      initContainers:
      - name: git-sync-init
        image: registry.k8s.io/git-sync/git-sync:v4.2.4
        env:
        - name: GITSYNC_REPO
          value: "https://github.com/nanajich-spec/Dags.git"
        - name: GITSYNC_ROOT
          value: "/git"
        - name: GITSYNC_DEST
          value: "dags"
        - name: GITSYNC_BRANCH
          value: "main"
        - name: GITSYNC_ONE_TIME
          value: "true"
        volumeMounts:
        - name: dags
          mountPath: /git
      containers:
      - name: airflow-worker
        image: apache/airflow:3.1.7
        command:
        - airflow
        - celery
        - worker
        env:
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/git/Dags.git"
        envFrom:
        - configMapRef:
            name: airflow-config
        volumeMounts:
        - name: dags
          mountPath: /git
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.2.4
        env:
        - name: GITSYNC_REPO
          value: "https://github.com/nanajich-spec/Dags.git"
        - name: GITSYNC_ROOT
          value: "/git"
        - name: GITSYNC_DEST
          value: "dags"
        - name: GITSYNC_BRANCH
          value: "main"
        - name: GITSYNC_PERIOD
          value: "10s"
        volumeMounts:
        - name: dags
          mountPath: /git
      volumes:
      - name: dags
        emptyDir: {}
